### ISSUE TITLE
Roanoke River Checklist

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#142]
### Find Reservoir Withdrawals that need appropriate available_mgd variant
1. Use view in https://github.com/HARPgroup/vahydro/wiki/River-Segment-Summed-Model-Properties which tells if they are marked as "reservoir" subtype. see Query below:
```
 select hydroid, substring(propname, 1, 24), fac_value, mp_riverseg_value, model_rseg, model_pid, elementid from tmp_any_sum_updated where reservoir > 0 and ftype not in ('hydropower', 'commercial', 'irrigation') and model_rseg like 'OR%' order by mp_riverseg_value DESC;

 hydroid |        substring         | fac_value |    mp_riverseg_value    |         model_rseg          | model_pid | elementid
---------+--------------------------+-----------+-------------------------+-----------------------------+-----------+-----------
   71956 | VIRGINIA BEACH SERVICE A |           |                      60 | OR7_8490_0000               |   4824962 |    306394
   73442 | BROOKNEAL WTP:Lower Fall |           |                      40 | OR2_7840_7970               |   4827853 |    306746
   74111 | ROANOKE (CITY) SERVICE A |           |                    27.9 | OR3_7740_8271_carvins       |   4828875 |    347363
   74123 | SPRING HOLLOW WTP:Spring |           |                   10.08 | OR2_8130_7900_spring_hollow |   4828910 |    351170
   72548 | SML SERVICE AREA:Smith M |           |  6.31780821917808219178 | OR4_8271_8120               |   4826201 |    351208
   73125 | SERVICE AREA:Roanoke Riv |           |  5.01369863013698630137 | OR7_8490_0000               |   4827237 |    306402
   74355 | CLARKSVILLE WTP:Kerr Lak |           |                       5 | OR7_8470_8490               |   4829218 |    307618
   73151 | CLARKSVILLE FINISHING PL |           |             4.948387097 | OR7_8470_8490               |   4976920 |    307624
   71642 | Bedford Central Water Tr |           |                     4.5 | OR2_7610_7780               |   4824402 |    351172
   73042 | MECKLENBURG POWER STATIO |           | 3.801369863013698630137 | OR7_8470_8490               |   4827076 |    351212
   71736 | LAWYERS ROAD PLANT:Lower |           |             2.388064516 | OR2_7780_7890               |   4824556 |    307986
   71652 | KEYSVILLE WTP:Roanoke Ri |           |                   2.016 | OR5_7910_8410               |   4824451 |    351238
   73172 | FALLING CR/BEAVERDAM CR  |           |                   1.516 | OR4_8271_8120               |   4827349 |    306492
   73522 | RIVER RIDGE SERVICE AREA |           |             0.045967742 | OR7_8490_0000               |   4977032 |    351186
(14 rows)
```
2. Sort through the above and , selecting only those that are in fact within model segments that have impoundments, and are properly structured (for example, we would not Loudoun water is NOT properly structured, since it is a pump store but the water demand element is in the same element as the Quarry. This needs to be reconfigured.
```
for i in 4827076 4976920 4829218 4826201 ; do ./modules/om/sh/set_reservoir_system_props.sh $i; done

```

**Comment by jdkleiner** [comment]
#### Query [available_mgd] model properties: 
```sql
SELECT hydroid, 
       substring(tmp_any_sum_updated.propname, 1, 24), 
       model_rseg, 
       model_pid, 
       dh_properties.propcode AS available_mgd
FROM tmp_any_sum_updated 
  LEFT OUTER JOIN dh_properties 
  ON (
    model_pid = featureid 
    AND dh_properties.entity_type = 'dh_properties' 
    AND dh_properties.propname = 'available_mgd'
  )
WHERE reservoir > 0 AND ftype NOT IN ('hydropower', 'commercial', 'irrigation') 
AND (model_rseg LIKE 'OR%' OR model_rseg LIKE 'OD%') 
ORDER BY model_rseg DESC;
```

```
 hydroid |        substring         |         model_rseg          | model_pid |       available_mgd
---------+--------------------------+-----------------------------+-----------+----------------------------
   73522 | RIVER RIDGE SERVICE AREA | OR7_8490_0000               |   4977032 | (Qintake - flowby) / 1.547
   73125 | SERVICE AREA:Roanoke Riv | OR7_8490_0000               |   4827237 | (Qintake - flowby) / 1.547
   71956 | VIRGINIA BEACH SERVICE A | OR7_8490_0000               |   4824962 | (Qintake - flowby) / 1.547
   73151 | CLARKSVILLE FINISHING PL | OR7_8470_8490               |   4976920 | impoundment_use_remain_mg
   73042 | MECKLENBURG POWER STATIO | OR7_8470_8490               |   4827076 | impoundment_use_remain_mg
   74355 | CLARKSVILLE WTP:Kerr Lak | OR7_8470_8490               |   4829218 | impoundment_use_remain_mg
   71652 | KEYSVILLE WTP:Roanoke Ri | OR5_7910_8410               |   4824451 | (Qintake - flowby) / 1.547
   72548 | SML SERVICE AREA:Smith M | OR4_8271_8120               |   4826201 | impoundment_use_remain_mg
   73172 | FALLING CR/BEAVERDAM CR  | OR4_8271_8120               |   4827349 | (Qintake - flowby) / 1.547
   74111 | ROANOKE (CITY) SERVICE A | OR3_7740_8271_carvins       |   4828875 | impoundment_use_remain_mg
   74123 | SPRING HOLLOW WTP:Spring | OR2_8130_7900_spring_hollow |   4828910 | impoundment_use_remain_mg
   73442 | BROOKNEAL WTP:Lower Fall | OR2_7840_7970               |   4827853 | (Qintake - flowby) / 1.547
   71736 | LAWYERS ROAD PLANT:Lower | OR2_7780_7890               |   4824556 | (Qintake - flowby) / 1.547
   71642 | Bedford Central Water Tr | OR2_7610_7780               |   4824402 | (Qintake - flowby) / 1.547
   72214 | MARTINSVILLE WTP:Smith R | OD3_8630_8720               |   4825396 | (Qintake - flowby) / 1.547
   73090 | SOUTH BOSTON QUARRY:Bani | OD3_8520_8621               |   4976892 | (Qintake - flowby) / 1.547
   73573 | GRETNA WTP:Banister Rive | OD3_8340_8520               |   4828084 | (Qintake - flowby) / 1.547
   74464 | STUART WTP:South Mayo Ri | OD1_8910_8930               |   4829386 | (Qintake - flowby) / 1.547
(18 rows)
```

**Comment by jdkleiner** [comment]
Final items to check: 
- CHATMOSS COUNTRY CLUB - (7.853 mgy): ows-vwuds-facility-info/73394
  - RB fixed a broadcast variable. Run and check out whether or not its data makes sense
  - Located in Roanoke Dan minor basin
- DANVILLE INDUSTRIAL WTP: ows-vwuds-facility-info/71603
  - Facility/Model needs 2040 value updated
  - Located in Roanoke Dan minor basin
- Virginia Beach Lake Gaston withdrawal - (8915.9 mgy): ows-vwuds-facility-info/71956
- Roanoke River Roanoke Rapids riverseg (below Kerr): ows-watershed-dash-info/67776
  - Contains the Virginia Beach Lake Gaston withdrawal - keep an eye on this segment

**Comment by jdkleiner** [comment]
Kerr Reservoir Model migrated from OM (5/8/20)

All reservoirs migrated from OM to VAHydro: batch-manage-properties?varkey=om_hydroimpoundment

Migrate Kerr Reservoir model:
`/var/www/html/d.dh drush src modules/om/src/om.migrate.element.php feature [omid] [hydroid]`
`/var/www/html/d.dh drush src modules/om/src/om.migrate.element.php feature 249383 168845`

Kerr Reservoir: 
- Kerr Lake watershed model: om-model-info/4709594
- Kerr Lake impoundment model: om-model-info/5769759

**Comment by jdkleiner** [comment]
- [ ] Look at all the withdrawals in the Smith Mountain Lake segment and see if they are withdrawing from the lake and make sure their "available_mgd = impoundment_use_remain_mg".
   - [ ] Smith Mountain and Leesville Dams, **vahydrosw_wshed_OR4_8271_8120**: ows-watershed-dash-info/68223

- [ ] RB cleared runs 11-20 in SML segment, so need to run all those scenarios again
   - [ ] Run from the Roanoke Rapids segment with the 2019-12-01 cache date, only the 3 segments between SML and RR will actually run and it will be done in a jiffy

**Comment by jdkleiner** [comment]
## Debugging 2030 Model Run (runid 12) - 2/23/21

- Issue: several river segments in the OD have elevated flows in the 2030 scenario 
- Cause: -	Leatherwood Creek had `Broadcast to Parent` AND `Send to Parent` broadcasts, which resulted in double counting 
   - http://deq2.bse.vt.edu/d.dh/om-model-info/4705014
- Solution: 
   - Deleted the `Broadcast to Parent` broadcast
   -  Reran run 12 from the containing Smith River below Martinsville VA segment: http://deq2.bse.vt.edu/d.dh/om-model-info/4705027
   - Reran all segments from Dan River @ Kerr Reservoir: http://deq2.bse.vt.edu/d.dh/om-model-info/4709440
