### ISSUE TITLE
VWP Model Setup Checklist

### ISSUE THREAD

**Issue by jdkleiner** [HARPgroup/vahydro#495]
### MODEL SETUP CHECKLIST _(Last revised 1/27/22)_

This list is intended to be used at the beginning of modeling projects to ensure all model components are updated/verified prior to running model scenarios.

On Facility:Riverseg Model:
- [ ] `fac_current_mgy` = 1521.199 **(This is the facility's total use 5-year avg sw+gw)**
   - Re-save the `linked_property` under `fac_current_mgy` to auto-update the value to match the _facility_ `wd_current_mgy`
   - Remember: `wd_current_mgy` is updated for every facility as a part of the annual QA cycle
- [ ] `current_mgy` = 1063.839 **(This is the facility's 5-year average demand from _surface water_ in this river segment)**
   - SQL for updating `current_mgy` for all facilities that have updated data:
      - https://github.com/HARPgroup/vahydro/wiki/Partitioning-Demands-for-WSP-Systems-to-Facilities
      - For updating `current_mgy` for a **single facility**, change the following in SQL above `where model_pid = 4827216`
         - Then manually take the value returned to set `current_mgy` on the facility model
   - This gets used in `current_mgd`, and in the `riverseg_frac`
- [ ] `current_mgd` = `current_mgy * historic_monthly_pct / modays`
   - This is the demand used in "current" model scenarios - see below: `base_demand_mgd`
   - Note: All facility models `current_mgd` should equal `current_mgy * historic_monthly_pct / modays`
- [ ] `vwp_max_mgd` = 8 _(Value comes from permit, enter manually)_
- [ ] `vwp_max_mgy` = 2920.0 _(Value comes from permit, enter manually)_
- [ ] `sw_frac` & `gw_frac`
   - `sw_frac` = 0.69934242659901827440
   - `gw_frac` = 0.30065757340098172560
   - `gw_sw_factor` = `gw_frac / sw_frac`
   - 2-Step Process to update these values:
      1) Update the `sw_frac` and `gw_frac` properties on the _facility_ using shell script: https://github.com/HARPgroup/vahydro/blob/master/drupal/dh_wsp/sh/set_use_fractions.sh
         - `jkleiner@deq3:/var/www/html/d.dh$ ./modules/dh_wsp/sh/set_use_fractions.sh [facility hydroid]`
      2) Then re-save `sw_frac` and `gw_frac` on the _model_ to auto-update the values
- [ ] `fac_demand_mgd` = `fac_demand_mgy * riverseg_frac * historic_monthly_pct / modays`
   - `fac_demand_mgy` = matrix by run mode, `0` or wsp demand such as `wsp2020_2020_mgy`
   - `riverseg_frac` = `current_mgy / fac_current_mgy`
- [ ] `gw_demand_mgd` = lookup based on run_mode
   - `historic_gw_mgd` = `gw_sw_factor * fac_demand_mgd * (1.0 - drought_pct)`
   - `current_gw_mgd` = `gw_sw_factor * current_mgd * (1.0 - drought_pct)`
   - `vwp_demand_gw_mgd` = `current_gw_mgd`
   - `vwp_prop_gw_mgd` = `current_gw_mgd`
   - `gw_fac_demand_mgd` = `gw_sw_factor * fac_demand_mgd * (1.0 - drought_pct)`
- [ ] `historic_monthly_pct` = matrix of values by month
   - 2-Step Process to update these values:
      1) Update the `wd_current_mon_factors` property on the _facility_ by manually opening and re-saving that property
      2) Then on the _model_ re-save the `linked_property` under `historic_monthly_pct` to auto-update the values to match the facility `wd_current_mon_factors`
- [ ] `vwp_exempt_mgd` = vwp_demand_mgd
   - If permitted, this will = vwp_demand_mgd
   - If not permitted, manually set exempt value to equal "Final Exempt Value (MGD)" found here: d.dh/ows-grandfathered-users
- [ ] `permit_status` = reissue (_since we want to model the reissuance of the existing permit_)
- [ ] `consumption` = `consumption_monthly`
   - `consumption_monthly` = matrix of values by month, uses default method for CWS
   - Update the `consumption_monthly` property on the model by manually opening and re-saving that property
- [ ] `unmet_demand_mgd` = `base_demand_mgd - wd_mgd`
- [ ] `discharge_mgd` = `ps_enabled * ( (1.0 - consumption - unaccounted_losses) * wd_mgd + discharge_from_gw_mgd)`
   - `ps_enabled` = 1 (matrix based on runmode)
   - `unaccounted_losses` = 0.10 (0.10 used as a default for municipal systems)
   - `discharge_from_gw_mgd` = `(1.0 - consumption - unaccounted_losses) * gw_demand_mgd`
- [ ] `base_demand_mgd` = matrix by runid, options include `historic_mgd`, `current_mgd`, `base_demand_pstatus_mgd`, `vwp_exempt_mgd`
   - `base_demand_pstatus_mgd` = (matrix by permit status, see `vwp_demand_mgd`) 
      - `vwp_demand_mgd` = `min(vwp_base_mgd, vwp_max_mgd)` See `vwp_base_mgd`
         - `vwp_base_mgd` = `vwp_max_mgy * historic_monthly_pct / modays`
- [ ] `max_mgd` = `base_demand_mgd`
- [ ] `adj_demand_mgd` = `(base_demand_mgd * (1.0 - drought_response_enabled * drought_pct) ) * (1.0 - rejected_demand_pct)`
   - `drought_response_enabled` = 1 or 0
   - `drought_pct` = matrix of pct reductions based on `drought_status`
- [ ] `available_mgd` = `(Qintake - flowby) / 1.547`
   - `flowby` = matrix by run mode (`flowby_historic`, `flowby_current`, `flowby_proposed`)
      - `flowby_current` = NULL
      - `flowby_proposed` = `flowby_current`
- [ ] **`wd_mgd` = `min(max_mgd,available_mgd,adj_demand_mgd)`**

---
On Riverseg Model:
- [ ] 0. River Channel Object
   - `demand` = `imp_off * wd_mgd * 1.54`

**Comment by jdkleiner** [comment]
Moved to wiki: https://github.com/HARPgroup/vahydro/wiki/VWP-Model-Setup-Checklist
