### ISSUE TITLE
Week of 7/5/2022

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#619]
- [ ] Permit modeling
  - [ ] Schedule 1 and 2 day sessions with Joey
  - [ ] Run James up to date hydrology (P6)
- [ ] Modeling next gen
  - [ ] start repo for channel routing work
  - [ ] share repo with Gopal
- [ ] HARP hsp2
  - [ ] Week 5 HARP meeting
  - [ ] Train/demo REST+Data model for land segment models and run data https://github.com/HARPgroup/HARParchive/issues/242
  - [ ] Begin visualization using saved CSVs (maybe demo summarize/xxx.R scripts)
- [ ] HSP2 development
  - [ ] Draft structure for hsp2 ops model https://github.com/respec/HSPsquared/issues/90
  - [ ] Check in on hdf file size issue https://github.com/respec/HSPsquared/issues/94
- [x] Support GW2 migration process
