### ISSUE TITLE
Week of 2022/08/01

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#650]
- [ ] Permit modeling
  - [ ] Schedule 2nd session with Joey
  - [ ] Do Monticello/Rivanna analysis  #624 
- [ ] Modeling next gen
  - [ ] github code initialization with Gopal
- [ ] HSP2 development
  - [ ] Finish switch to add hsp2 to cbp executable p6 all. https://github.com/HARPgroup/cbp_wsm/issues/64  
  - [ ] Update object and code design plan on respec
  - [ ] Plan object meeting with Joey and Gavriel
  - [ ] Test prototype code for withdrawals: https://github.com/HARPgroup/HSPsquared/issues/12
  - [ ] Plan and implement data storage framework tweaks (how to get data into and out of h5, and to share amongst objects)
  - [ ] Review testing environment and/or strategy set up with Joey https://github.com/HARPgroup/HSPsquared/issues/6
- [x] #648
- [ ] Drought
  - [ ] climate change scenario test
- [ ] Support VAHydro migration process as needed
