### ISSUE TITLE
Week of 2022/08/15

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#658]
- [ ] Permit modeling
  - [ ] Schedule 2nd session with Joey
  - [ ] Finish Monticello/Rivanna analysis  #624 
  - [ ] #656
- [ ] Modeling next gen
  - [ ] Review wdm_insert_one with Gopal
- [ ] HARP project
  - [ ] gather info on student staffing for the semester and choose appropriate tasks
- [ ] HSP2 development
  - [ ] Add automated summary routine call in p5 river 
  - [ ] Finish switch to add hsp2 to cbp executable p6 all. https://github.com/HARPgroup/cbp_wsm/issues/64  
  - [ ] Update object and code design plan on respec
  - [ ] Test prototype code for withdrawals: https://github.com/HARPgroup/HSPsquared/issues/12
  - [ ] Plan and implement data storage framework tweaks (how to get data into and out of h5, and to share amongst objects)
  - [ ] Finish testing environment set up https://github.com/HARPgroup/HSPsquared/issues/6
  - [x] #657
- [ ] Drought
  - [ ] climate change scenario test
- [ ] Support VAHydro migration process as needed
