### ISSUE TITLE
Week of 9/26/2022

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#684]
- [ ] HARP https://github.com/HARPgroup/HARParchive/issues/544
  - [ ] Finalize fallback vahydro routine for FTABLE floodplains
    - [ ] get with Joey since I will be out of town for the Thursday meeting
  - [ ] full port of old OM river segment analyses
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [ ] list of function needed to unite via WDM
  - [ ] verify and document `/usr/local/bin/get_config`
  - [ ] verify `check_met` and allow it to guess the scenario? (Use get_config)
  - [ ] flesh out routines/files needed to parameterize a river segment https://github.com/HARPgroup/cbp_wsm/issues/85
- [ ] P6 runtime
  - [ ] Check on Potomac test run in new framework
- [ ] spring creek tech eval reviewed and put in VWP folder #538
