### ISSUE TITLE
Weejk of 2022/10/03

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#686]
- [ ] HARP https://github.com/HARPgroup/HARParchive/issues/544
  - [ ] Finalize fallback vahydro routine for FTABLE floodplains
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [ ] list of function needed to unite via WDM
  - [ ] flesh out routines/files needed to parameterize a river segment https://github.com/HARPgroup/cbp_wsm/issues/85
- [ ] hsp2
  - [ ] fix the specl parser to read in the OPERATION correctly.
- [ ] P6 runtime
  - [ ] Check on Potomac test run in new framework
- [ ] spring creek tech eval reviewed and put in VWP folder #538
