### ISSUE TITLE
Week of 2022/10/24

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#703]
- [x] Denton: HARPgroup/vahydro#698 
  - [ ] Confirm certificate update needs timeline with Denton
- [ ] HARP HARPgroup/HARParchive#610 
  - [ ] help denton with permissions problem
  - [ ] flesh out routines/files needed to parameterize a river segment hydro stuff https://github.com/HARPgroup/cbp_wsm/issues/85
  - [ ] flesh out routines/files needed to parameterize a river segment land use https://github.com/HARPgroup/cbp_wsm/issues/85
  - [ ] Review summarize work from last week
  - [ ] check in with Scotty on Meghan next steps and if we should do standard meeting or work session this week?
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [x] HARPgroup/meta_model#6
- [ ] hsp2
  - [x] HARPgroup/HSPsquared#33
  - [ ] Finish Draft Data Model HARPgroup/HSPsquared/issues/20
  - [ ] HARPgroup/vahydro#697
  - [ ] HARPgroup/vahydro#696
  - [ ] Finalize HARPgroup/HSPsquared/issues/31
- [ ] P6/meta-model runtime
  - [ ] carry over bug fix with ann/avg load calcs into p6 `hsp2`? Note: must use a watershed that has NOT been run for `vadeq_2021` because if so, the missing WDMs *may* be there since it uses `vadeq_2021` for runoff.  Try NF Shenandoah
  - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)
- [ ] VWP
  - [ ] Integrate HARPgroup/vahydro#656
  - [x] Permit Scoping HARPgroup/vahydro#700
- [ ] Drought: plan w/JK climate change scenario test HARPgroup/vahydro#606
- [ ] Bullets relating value added by J Shortridge for swk by end of October: keep it high level, just what JS brings to the table as an academic and extension rep.
- [ ] Test Rapp update/append WDM HARParchive/issues/173
- [ ] General infrastructure: 
  - [ ] What task are we going to automate?  With @jdkleiner I nominate setting up project maps properties to automatically generate a map for VWP, but also for user in next WSP and in annual report, and to insure that we can to a % change or Net change for any property metric.
  - [ ] plan NHDplus to-node import to vahydro using column `PlusFlowlineVAA_ToNode` in file `/var/www/html/files/nhd/NHDPlusFlowlines.csv` (on deq1 and deq2)
- [v] CEDS Migration support
