### ISSUE TITLE
Week of 2022/10/31

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#712]
- [ ] HARP HARPgroup/HARParchive#617\
  - [ ] flesh out routines/files needed to parameterize a river segment hydro stuff https://github.com/HARPgroup/cbp_wsm/issues/85
  - [ ] flesh out routines/files needed to parameterize a river segment land use https://github.com/HARPgroup/cbp_wsm/issues/85
  - [ ] check in with Scotty on Meghan next steps and if we should do standard meeting or work session this week?
  - [ ] River Segment Generator (see also: #704)
- [ ] hsp2
  - [ ] Finish Draft Data Model HARPgroup/HSPsquared/issues/20
  - [ ] Add UVQUAN support (first step to allow testing of data model) https://github.com/respec/HSPsquared/issues/106
  - [ ] Links: HARPgroup/vahydro#697
  - [ ] Parser: HARPgroup/vahydro#696 
  - [ ] Finalize HARPgroup/HSPsquared/issues/31 
  - [ ] Plan tasks for HSPsquared/issues/25
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [ ] test running appended met in meta-model framework https://github.com/HARPgroup/HARParchive/issues/173#issuecomment-1289261525
  - [ ] carry over bug fix with ann/avg load calcs into p6 `hsp2`? Note: must use a watershed that has NOT been run for `vadeq_2021` because if so, the missing WDMs *may* be there since it uses `vadeq_2021` for runoff.  Try NF Shenandoah
  - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)\
- [ ] VWP
  - [ ] Integrate HARPgroup/vahydro#656\
- [ ] Drought:  
  - [ ] plan w/JK climate change scenario test HARPgroup/vahydro#606\
- [ ] Bullets relating value added by J Shortridge for swk by end of October: keep it high level, just what JS brings to the table as an academic and extension rep.
- [ ] Test Rapp update/append WDM HARParchive/issues/173\
  - [ ] Then do a 2nd version for p5 using append mode
- [ ] General infrastructure: 
  - [ ] What task are we going to automate?  With @jdkleiner I nominate setting up project maps properties to automatically generate a map for VWP, but also for user in next WSP and in annual rep they finally got me in the loop.ort, and to insure that we can to a % change or Net change for any property metric.
    - [ ] Daily pydrotools script to generate a summary pdf https://github.com/HARPgroup/pydro-tools/issues/16
    - [ ] Map generation for VWP/modeling project: https://github.com/HARPgroup/hydro-tools/issues/350 
  - [ ] plan NHDplus to-node import to vahydro using column `PlusFlowlineVAA_ToNode` in file `/var/www/html/files/nhd/NHDPlusFlowlines.csv` (on deq1 and deq2)
- [ ] CEDS Migration support\
- [x] Sign up for refresh 
- [ ] STAC #709
  - [ ] Choose slides from May 2022 presentation
  - [ ] run past mgmt
