### ISSUE TITLE
Week of 2022/12/12

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#732]
- [ ] HARP https://github.com/HARPgroup/HARParchive/issues/652
  - [ ] flesh out routines/files needed to parameterize a river segment hydro stuff https://github.com/HARPgroup/cbp_wsm/issues/85
  - [ ] pick a northern and southern river pilot watershed.  Each with at least 1 custom sub-watershed in it. Once we find the target watershed, expand the study area to include the entire WSP planning basin (get with planners to learn about these new hydro boundaries)
  - [ ] River Segment Generator (see also: #704)
- [ ] hsp2
  - [ ] Finish Draft Data Model HARPgroup/HSPsquared/issues/20
  - [ ] Add UVNAME support (first step to allow testing of data model) https://github.com/respec/HSPsquared/issues/106
  - [ ] Links: HARPgroup/vahydro#697
  - [ ] Parser: HARPgroup/vahydro#696 
  - [ ] Finalize HARPgroup/HSPsquared/issues/31 
  - [ ] Functionalize state tests for DataMatrix and test speed options for only reading vars from state vs. read constants also https://github.com/HARPgroup/HSPsquared/issues/41
  - [x] Further Performance testing and design for equation eval HARPgroup/HSPsquared/issues/25
  - [x] Do object code for equation to create full life cycle, add `state_ix` entries, get links https://github.com/HARPgroup/HSPsquared/issues/38#issuecomment-1338171031
  - [x] #728
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [ ] carry over bug fix with ann/avg load calcs into p6 `hsp2`? Note: must use a watershed that has NOT been run for `vadeq_2021` because if so, the missing WDMs *may* be there since it uses `vadeq_2021` for runoff.  Try NF Shenandoah
  - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)\
- [ ] VWP
  - [ ] Integrate HARPgroup/vahydro#656
  - [ ] Quick setup for Kyanite #715 
- [ ] Drought:  
  - [ ] plan w/JK climate change scenario test HARPgroup/vahydro#606
  - [ ] bug fix for drought map: https://github.com/HARPgroup/vahydro/issues/731
- [ ] Bullets relating value added by J Shortridge for swk by end of October: keep it high level, just what JS brings to the table as an academic and extension rep.
- [ ] Test Rapp update/append WDM HARParchive/issues/173
  - [ ] Then do a 2nd version for p5 using append mode
- [ ] General infrastructure: 
  - [ ] What task are we going to automate?  With @jdkleiner I nominate setting up project maps properties to automatically generate a map for VWP, but also for user in next WSP and in annual rep they finally got me in the loop.ort, and to insure that we can to a % change or Net change for any property metric.
    - [ ] Daily pydrotools script to generate a summary pdf https://github.com/HARPgroup/pydro-tools/issues/16
    - [ ] Map generation for VWP/modeling project: https://github.com/HARPgroup/hydro-tools/issues/350 
  - [ ] plan NHDplus to-node import to vahydro using column `PlusFlowlineVAA_ToNode` in file `/var/www/html/files/nhd/NHDPlusFlowlines.csv` (on deq1 and deq2)
- [ ] CEDS Migration support
- [ ] Get this book: https://link.springer.com/book/10.1007/978-1-4614-5833-3
- [ ] Process for Potomac for Scott
  - [ ] ID low-flow habitat sensitive species in Potomac
  - [ ] Collect historical abundance sampling of these species in question (especially 1960 forward)
  - [ ] Use lidar to determine wetted perimeter flow-habitat changes
  - [ ] run scenarios with 100,200 and 500 MGD flowbys
- [ ] Enable/disable postgres boot https://askubuntu.com/questions/539187/how-to-make-postgres-start-automatically-on-boot
