### ISSUE TITLE
Week of 2023/05/15

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#838]
- [ ] HARP Project
   - [ ] Plan CU/available calcs outline https://github.com/HARPgroup/HARParchive/issues/818 
   - [ ] Review CU/available with WSP crew
- [ ] hsp2
   - [ ] Facility model parsing & testing with withdrawal https://github.com/HARPgroup/HSPsquared/blob/spects/tests/testcbp/HSP2results/load_facility_json.py
- [ ] VWP
   - [ ] Map generator with JK https://github.com/HARPgroup/hydro-tools/issues/369
   - [x] Iluka modeling TE Crewe #631 
   - [ ] Appomattox CIA prep (do additional downstream review in prep for comments per JGrist) #342 
- [ ] General:
    - [ ] Review modeling with Weedon #832 
    - [ ] SQL finalize with G&B: #825
