### ISSUE TITLE
Week of 2023/05/29

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#845]
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [ ] Add hsp2_cbp5 to framework
  - [ ] Add hspf_cbp5 to framework
  - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)
- [ ] HARP Project
   - [ ] Run the summary for completed scenarios https://github.com/HARPgroup/HARParchive/issues/659
   - [ ] Model Migration/HARP https://github.com/HARPgroup/HARParchive/issues/652 
- [ ] hsp2
   - [ ] micro sub-watershed testing development https://github.com/HARPgroup/HSPsquared/issues/16
   - [ ] outline parser finalization
   - [ ] Facility model parsing & testing
   - [ ] full BC test with simple routing & parsing
   - [ ] Work on new version facility model https://github.com/HARPgroup/HARParchive/issues/744
   - [ ] Statistic https://github.com/HARPgroup/HSPsquared/issues/63
- [ ] VWP
   - [ ] Revisit Beaver Creek to determine model run issue in mode 4: https://github.com/HARPgroup/vahydro/issues/780
   - [ ] Prep Kilby #614 
   - [x] Appomattox CIA prep (do additional downstream review in prep for comments per JGrist) #342 
   - [ ] list of items to keep the modeling on track: keep data coordinator position, staffed, do drought, modeling and analysis, not drought management, task force, administration, complete draft TE by the 15th, coordinate with applicant and have any additional scenarios decided by the 21st, and finalize annual demand at maximum daily demand during water supply plan coordination, ensure that all permits that are to be included in a watershed CIA have the correct magnitude, or when there are multiple BWP permits under development in a single watershed, ensure coordination occurs at approximate time if possible.
 - [ ] Drought:
    - [ ] plan w/JK climate change scenario test https://github.com/HARPgroup/vahydro/issues/606
    - [ ] NLDAS model update
    - [ ] Test Rapp update/append WDM HARParchive/issues/173
       - [ ] Then do a 2nd version for p5 using append mode
       - [ ] https://github.com/HARPgroup/vahydro/issues/749
    - [ ] What task are we going to automate? With @jdkleiner I nominate setting up project maps properties to automatically generate a map for VWP, but also for user in next WSP and in annual rep they finally got me in the loop.ort, and to insure that we can to a % change or Net change for any property metric.
    - [ ] Daily pydrotools script to generate a summary pdf https://github.com/HARPgroup/pydro-tools/issues/16
- [ ] General:
    - [ ] Save LEN #842 842
    - [ ] plan NHDplus to-node import to vahydro using column PlusFlowlineVAA_ToNode in file /var/www/html/files/nhd/NHDPlusFlowlines.csv (on deq1 and deq2)
    - [ ] CEDS Migration support
    - [ ] Get this book: https://link.springer.com/book/10.1007/978-1-4614-5833-3
    - [ ] Update [Gant chart on HSP2 project / sharepoint](https://covgov.sharepoint.com/:x:/s/deqnet/EaeMJ3KyRqZDuL5X2hA7ZSEB9Bk1DydneB966YeRQNu8QQ?e=kVekxs)
