### ISSUE TITLE
Week if 2023/09/25

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#909]
- Beaver Creek: I'm gonna ship this out today.  This one should be fairly straight-forward as most of the details have been worked out with their modeler so hopefully this will spell the end of the backlog!
- Mott's Run/Hunting Run: this is one of the next permits up to bat, while the VWP folks aren't ready to request modeling, I am going to do some more prep work on this as it is a complex system in a highly scrutinized (and pumped) watershed, and I want to be ready to really nail this when the time comes.
- Shenandoah drought -- things are clearly looking better!  I am going to try to spend a little but of time on drought modeling in general, and in this area in specific and take some notes for lessons learned.  My honest opinion is that with the weather forecast and recent events that we should be out of the immediate danger zone for the next couple of months, but this winter recharge period is a critical time for us to start monitoring this area closely.  I will keep you and Trevor up to date with whatever I am doing.  Please let me know if you have any specific objectives or guidance on this front.
- Reach out to my network of modeling aficionados this week to see who is looking for a challenge.
- Thursday weekly VWP meeting get a sense of their needs and any last follow-ups with Joey before he departs.
- Shad recovery meeting this Wednesday at the Rice Center - it's a big one, 9am to 4pm.
- Work up a summary of the things that we need to tackle in the fall/winter months, and particularly highlight those areas that Joey did most of the heavy lifting on, especially areas where he helped out the planners with data management, and I will be prepared to discuss that whenever and wherever you like.  Focus on Joey to Brendan knowledge transfer areas

- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [ ] Add hsp2_cbp5 to framework
  - [ ] Add hspf_cbp5 to framework
  - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)
- [ ] HARP Project
   - [ ] Important model error planning meeting
   - [ ] Run the summary for completed scenarios https://github.com/HARPgroup/HARParchive/issues/659
   - [ ] Plan baseline flow (zero withdrawal) model (see also HARPgroup/vahydro#844 and https://github.com/HARPgroup/HARParchive/issues/744)
- [ ] hsp2
   - [x] SimpleChannel object creation https://github.com/HARPgroup/HSPsquared/issues/77
      - [ ] micro sub-watershed testing development https://github.com/HARPgroup/HSPsquared/issues/16
      - [ ] full BC test with simple routing & parsing
   - [x] HARPgroup/HSPsquared#79
   - [ ] Extensive testing of header line in DataMatrix https://github.com/HARPgroup/HSPsquared/issues/26
   - [ ] Test broadcasts https://github.com/HARPgroup/HSPsquared/issues/36
   - [ ] Do testing branches to ascertain code bottlenecks https://github.com/HARPgroup/HSPsquared/issues/66
   - [ ] outline parser finalization
   - [ ] test runoff timeseries grabbing into ts_ix
   - [ ] Watershed/Sub-watershed model/river segment template development https://github.com/HARPgroup/HSPsquared/issues/58
   - [ ] Continue facility model migration script HARPgroup/vahydro#844 
   - [ ] Work on new version facility model https://github.com/HARPgroup/HARParchive/issues/744
      - [ ] Continue facility model migration script HARPgroup/vahydro#844 
   - [ ] Why does dynamic loading differ in Win/Lin? HARPgroup/HSPsquared#73
   - [ ] Statistic https://github.com/HARPgroup/HSPsquared/issues/63
- [ ] VWP
   - [ ] Ship Bever Creek TE
   - [ ] Habitat in Cobb's/Henrico
- [ ] Drought:
   - [ ] plan climate change scenario test https://github.com/HARPgroup/vahydro/issues/606
   - [ ] Finish & Test Drought mashup for Potomac https://github.com/HARPgroup/vahydro/issues/606#issuecomment-1591365841
   - [ ] Test Rapp update/append WDM HARParchive/issues/173
      - [ ] Then do a 2nd version for p5 using append mode
      - [ ] https://github.com/HARPgroup/vahydro/issues/749
   - [ ] What task are we going to automate? With @jdkleiner I nominate setting up project maps properties to automatically generate a map for VWP, but also for user in next WSP and in annual rep they finally got me in the loop.ort, and to insure that we can to a % change or Net change for any property metric.
   - [ ] Daily pydrotools script to generate a summary pdf https://github.com/HARPgroup/pydro-tools/issues/16
- [ ] General:
    - [ ] Save LEN HARPgroup/vahydro#842 842
    - [ ] plan NHDplus to-node import to vahydro using column PlusFlowlineVAA_ToNode in file /var/www/html/files/nhd/NHDPlusFlowlines.csv (on deq1 and deq2)
    - [x] CEDS Migration support
    - [ ] Get this book: https://link.springer.com/book/10.1007/978-1-4614-5833-3
    - [ ] Update [Gant chart on HSP2 project / sharepoint](https://covgov.sharepoint.com/:x:/s/deqnet/EaeMJ3KyRqZDuL5X2hA7ZSEB9Bk1DydneB966YeRQNu8QQ?e=kVekxs)
