### ISSUE TITLE
Week of 2023/10/02

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#914]
### Overview
- Mott's Run/Hunting Run: do some more prep work on this as it is a complex system in a highly scrutinized (and pumped) watershed.
- Shenandoah drought
- Channel modeling work in new hsp2: deploy tester for empirical method, migrate Gopal's code if available (send email to him to see if he is ready to stash in github)
- Work up a summary of the things that we need to tackle in the fall/winter months, and particularly highlight those areas that Joey did most of the heavy lifting on, especially areas where he helped out the planners with data management, and I will be prepared to discuss that whenever and wherever you like.  Focus on Joey to Brendan knowledge transfer areas

### Tasks
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [ ] Add hsp2_cbp5 to framework
  - [ ] Add hspf_cbp5 to framework
  - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)
- [ ] HARP Project
   - [x] Important model error planning meeting
   - [ ] Run the summary for completed scenarios https://github.com/HARPgroup/HARParchive/issues/659
   - [ ] Plan baseline flow (zero withdrawal) model (see also HARPgroup/vahydro#844 and https://github.com/HARPgroup/HARParchive/issues/744)
   - [x] Planning call with Scotty
- [ ] hsp2
   - [ ] SimpleChannel object work https://github.com/HARPgroup/HSPsquared/issues/77
      - [ ] Implement Gopal's new math
      - [ ] micro sub-watershed testing development https://github.com/HARPgroup/HSPsquared/issues/16
      - [ ] full BC test with simple routing & parsing
      - [x] Error analysis of simple channel regression approach
   - [ ] HARPgroup/HSPsquared#79
   - [ ] Extensive testing of header line in DataMatrix https://github.com/HARPgroup/HSPsquared/issues/26
   - [ ] Test broadcasts https://github.com/HARPgroup/HSPsquared/issues/36
   - [ ] Do testing branches to ascertain code bottlenecks https://github.com/HARPgroup/HSPsquared/issues/66
   - [ ] outline parser finalization
   - [ ] test runoff timeseries grabbing into ts_ix
   - [ ] Watershed/Sub-watershed model/river segment template development https://github.com/HARPgroup/HSPsquared/issues/58
   - [ ] Continue facility model migration script HARPgroup/vahydro#844 
   - [ ] Work on new version facility model https://github.com/HARPgroup/HARParchive/issues/744
      - [ ] Continue facility model migration script HARPgroup/vahydro#844 
   - [ ] Why does dynamic loading differ in Win/Lin? HARPgroup/HSPsquared#73
   - [ ] Statistic https://github.com/HARPgroup/HSPsquared/issues/63
- [ ] VWP
   - [x] Ship Beaver Creek TE
   - [ ] Habitat in Cobb's/Henrico
   - [x] Thursday weekly VWP meeting get a sense of their needs and any last follow-ups with Joey before he departs.
   - [ ] Planning meeting with VWP leadership
- [ ] Drought:
   - [ ] plan climate change scenario test https://github.com/HARPgroup/vahydro/issues/606
   - [ ] Finish & Test Drought mashup for Potomac https://github.com/HARPgroup/vahydro/issues/606#issuecomment-1591365841
   - [ ] Test Rapp update/append WDM HARParchive/issues/173
      - [ ] Then do a 2nd version for p5 using append mode
      - [ ] https://github.com/HARPgroup/vahydro/issues/749
   - [x] What task are we going to automate? With @jdkleiner I nominate setting up project maps properties to automatically generate a map for VWP, but also for user in next WSP and in annual rep they finally got me in the loop.ort, and to insure that we can to a % change or Net change for any property metric.
   - [x] Daily pydrotools script to generate a summary pdf https://github.com/HARPgroup/pydro-tools/issues/16
- [ ] General:
    - [x] Shad recovery meeting this Wednesday at the Rice Center - it's a big one, 9am to 4pm.
    - [x] Send emails out to Scotty and HARP network about modeler position opening up
    - [ ] Save LEN HARPgroup/vahydro#842 842
    - [ ] plan NHDplus to-node import to vahydro using column PlusFlowlineVAA_ToNode in file /var/www/html/files/nhd/NHDPlusFlowlines.csv (on deq1 and deq2)
    - [ ] CEDS Migration support
    - [ ] Joey's departing knowledge trnsfer
       - [ ] Annual e-blast support
       - [ ] Drought data analysis (just in case we get there and I need help)
       - [ ] Aquaveo data import -- you may have already done this together, and /or we may not even do this any more, but I recall there was a time when this is something Joey helped Curt with using R...
    - [ ] Get this book: https://link.springer.com/book/10.1007/978-1-4614-5833-3
    - [ ] Update [Gant chart on HSP2 project / sharepoint](https://covgov.sharepoint.com/:x:/s/deqnet/EaeMJ3KyRqZDuL5X2hA7ZSEB9Bk1DydneB966YeRQNu8QQ?e=kVekxs)
