### ISSUE TITLE
Week of 2023/10/16

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#921]
### Overview
- Review modeler EWP and suggest changes if I have thoughts.
- Channel modeling work in new hsp2: deploy tester for channel simulation
   - This has been really pushed to the side, and while this next 2 months VWP model schedule is nearly a full-time commitment, I want to get some work done on this as it is one of 2 big remaining hurdles for the HSP2 migration (both Channel code and Impoundment code are pending and crucial).
- VWP
   - Planning for next models (almost all PEEP), and scheduling with Liz.
   - Mott's Run/Hunting Run: do some more prep work on this as it is a complex system in a highly scrutinized (and pumped) watershed.
   - Get set up for Roanoke River SA model
   - Get set up for Richmond Kanawha modeling
- Shenandoah drought: keep chipping away at this as time is available.

### Tasks
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [ ] Add hsp2_cbp5 to framework
  - [ ] Add hspf_cbp5 to framework
  - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)
- [ ] HARP Project
   - [ ] Help debug the map render issue
   - [ ] Plan baseline flow (zero withdrawal) model (see also HARPgroup/vahydro#844 and https://github.com/HARPgroup/HARParchive/issues/744)
   - [ ] Decide on base map (stamen going $$, Google needs API, maybe VGIN?) https://github.com/HARPgroup/HARParchive/issues/1114
- [ ] hsp2
   - [ ] SimpleChannel object work https://github.com/HARPgroup/HSPsquared/issues/77
      - [ ] Implement Gopal's new math if available (send email to him to see if he is ready to stash in github)
      - [ ] micro sub-watershed testing development https://github.com/HARPgroup/HSPsquared/issues/16
      - [ ] full BC test with simple routing & parsing
   - [ ] HARPgroup/HSPsquared#79
   - [ ] Extensive testing of header line in DataMatrix https://github.com/HARPgroup/HSPsquared/issues/26
   - [ ] Test broadcasts https://github.com/HARPgroup/HSPsquared/issues/36
   - [ ] Do testing branches to ascertain code bottlenecks https://github.com/HARPgroup/HSPsquared/issues/66
   - [ ] outline parser finalization
   - [ ] test runoff timeseries grabbing into ts_ix
   - [ ] Watershed/Sub-watershed model/river segment template development https://github.com/HARPgroup/HSPsquared/issues/58
   - [ ] Continue facility model migration script HARPgroup/vahydro#844 
   - [ ] Work on new version facility model https://github.com/HARPgroup/HARParchive/issues/744
      - [ ] Continue facility model migration script HARPgroup/vahydro#844 
   - [ ] Why does dynamic loading differ in Win/Lin? HARPgroup/HSPsquared#73
   - [ ] Statistic https://github.com/HARPgroup/HSPsquared/issues/63
- [ ] VWP
   - [ ] Habitat in Cobb's/Henrico
   - [ ] continue Calibration analysis in Rapp #918 & #227 
      - [ ] Also: https://github.com/HARPgroup/HARParchive/issues/1110
   - [ ] Get the basic TE set up for Motts to include all relevant segments #439
   - [ ] Roanoke River SA model follow up 
- [ ] Drought:
   - [ ] plan climate change scenario test https://github.com/HARPgroup/vahydro/issues/606
   - [ ] Finish & Test Drought mashup for Potomac https://github.com/HARPgroup/vahydro/issues/606#issuecomment-1591365841
   - [ ] Test Rapp update/append WDM HARParchive/issues/173
      - [ ] Then do a 2nd version for p5 using append mode
      - [ ] https://github.com/HARPgroup/vahydro/issues/749
- [ ] General:
    - [ ] Save LEN HARPgroup/vahydro#842 842
    - [ ] plan NHDplus to-node import to vahydro using column PlusFlowlineVAA_ToNode in file /var/www/html/files/nhd/NHDPlusFlowlines.csv (on deq1 and deq2)
    - [ ] CEDS Migration support
    - [ ] Get this book: https://link.springer.com/book/10.1007/978-1-4614-5833-3
    - [ ] Update [Gant chart on HSP2 project / sharepoint](https://covgov.sharepoint.com/:x:/s/deqnet/EaeMJ3KyRqZDuL5X2hA7ZSEB9Bk1DydneB966YeRQNu8QQ?e=kVekxs)
