### ISSUE TITLE
Week of 2023/11/06

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#928]
### Overview
- Evaluating Potomac drought conditions -- work with Gopal on fixing/quantifying precip errors
- Getting started in earnest on the Motts and Hunting Run perrmit models 
- Bedford Hydro

### Tasks
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
  - [ ] Add hsp2_cbp5 to framework
  - [ ] Add hspf_cbp5 to framework
  - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)
- [ ] HARP Project
   - [x] Help debug the map render issue
   - [x] Review summary script changes in OM for calculating available water https://github.com/HARPgroup/om/pull/501
   - [ ] Plan baseline flow (zero withdrawal) model (see also HARPgroup/vahydro#844 and https://github.com/HARPgroup/HARParchive/issues/744)
   - [x] Decide on base map (stamen going $$, Google needs API, maybe VGIN?) https://github.com/HARPgroup/HARParchive/issues/1114
   - [ ] Come up with a good goal point to have a project demo and briefing for Hannah
- [ ] hsp2
   - [ ] SimpleChannel object work https://github.com/HARPgroup/HSPsquared/issues/77
      - [ ] Implement Gopal's new math if available (send email to him to see if he is ready to stash in github)
      - [ ] micro sub-watershed testing development https://github.com/HARPgroup/HSPsquared/issues/16
      - [ ] full BC test with simple routing & parsing
   - [ ] HARPgroup/HSPsquared#79
   - [ ] Extensive testing of header line in DataMatrix https://github.com/HARPgroup/HSPsquared/issues/26
   - [ ] Test broadcasts https://github.com/HARPgroup/HSPsquared/issues/36
   - [ ] Do testing branches to ascertain code bottlenecks https://github.com/HARPgroup/HSPsquared/issues/66
   - [ ] outline parser finalization
   - [ ] test runoff timeseries grabbing into ts_ix
   - [ ] Watershed/Sub-watershed model/river segment template development https://github.com/HARPgroup/HSPsquared/issues/58
   - [ ] Continue facility model migration script HARPgroup/vahydro#844 
   - [ ] Work on new version facility model https://github.com/HARPgroup/HARParchive/issues/744
      - [ ] Continue facility model migration script HARPgroup/vahydro#844 
   - [ ] Why does dynamic loading differ in Win/Lin? HARPgroup/HSPsquared#73
   - [ ] Statistic https://github.com/HARPgroup/HSPsquared/issues/63
- [ ] VWP
   - [ ] Habitat in Cobb's/Henrico
   - [ ] meet w/Kathy on Beaver Creek #884 
   - [ ] continue Calibration analysis in Rapp #918 & #227 
      - [ ] Also: https://github.com/HARPgroup/HARParchive/issues/1110
   - [ ] Get the basic TE set up for Motts to include all relevant segments #439 
   - [x] Haxall/Kanwha #916 
   - [ ] Roanoke River SA model follow up 
   - [x] Review Lake Kilby comments from DWR - meet w/Liz to decide on a trajectory
   - [ ] Review emails, VWP meeting notes and PEEP and update VWP project page https://github.com/orgs/HARPgroup/projects/4/views/1
- [ ] Drought:
   - [ ] #926
   - [ ] plan climate change scenario test https://github.com/HARPgroup/vahydro/issues/606
   - [ ] Finish & Test Drought mashup for Potomac https://github.com/HARPgroup/vahydro/issues/606#issuecomment-1591365841
   - [x] Why does `drought` scenario runoff work with OM and `drought` scen river works with `vadeq_2021` runoff, but `drought` RO + `drought` river = error? https://github.com/HARPgroup/cbp_wsm/issues/62#issuecomment-1771896039
   - [ ] Migrate met data and mashup processes into a meta_model workflow to allow multi-core with dependency at the landseg process step level
   - [x] Continue to try to debug the drought status override switch for precip indicators
   - [ ] Test Rapp update/append WDM HARParchive/issues/173
      - [ ] Then do a 2nd version for p5 using append mode
      - [ ] https://github.com/HARPgroup/vahydro/issues/749
- [ ] General:
    - [ ] Save LEN HARPgroup/vahydro#842 842
    - [ ] plan NHDplus to-node import to vahydro using column PlusFlowlineVAA_ToNode in file /var/www/html/files/nhd/NHDPlusFlowlines.csv (on deq1 and deq2)
    - [ ] CEDS Migration support
    - [x] Final review of modeler questions and selection of 9
    - [ ] Get this book: https://link.springer.com/book/10.1007/978-1-4614-5833-3
    - [ ] Update [Gant chart on HSP2 project / sharepoint](https://covgov.sharepoint.com/:x:/s/deqnet/EaeMJ3KyRqZDuL5X2hA7ZSEB9Bk1DydneB966YeRQNu8QQ?e=kVekxs)
