### ISSUE TITLE
Week of 2023/11/27

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#939]
- Interviews (M, W)
- Mott's Run - my main modeling priority this week. The focus is on examining the current permit and insuring that I have all ducks in a row, and see if there is any need to modify rules.
- Support Gouri on Bedford Hydro.  I plan on setting up a meeting with her to discuss where she is at on it, the model has been run successfully, and really the only obstacles are, as discussed, the language to describe why the normal view on instream flows do not apply in these types of bypassed reach situations.
- Documentation of process to add operational modules to hsp2: this is to organize all the docs that have been compiled along the way, to insure that 1) I have a good blueprint as I move forward on this, and 2) the others (new modeler) will have a reasonable cookbook to jump in on it.
- Support Denton (the Virginia Tech modeling system hardware and network admin) in the hardware replacement work.  The big task that I am involved in is to upgrade the main database.  This will likely involve a couple of hours of work on my part, and a couple of hours of thinking and reviewing any plans and correspondence from Denton.

Tasks
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
   - [ ] Add hsp2_cbp5 to framework
   - [ ] Add hspf_cbp5 to framework
   - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)
- [ ] HARP Project
   - [ ] Plan baseline flow (zero withdrawal) model (see also https://github.com/HARPgroup/vahydro/issues/844 and https://github.com/HARPgroup/HARParchive/issues/744)
   - [ ] Come up with a good goal point to have a project demo and briefing for Hannah
- [ ] hsp2
   - [ ] Document process for new ops/STATE module integration https://github.com/respec/HSPsquared/issues/105
   - [ ] SimpleChannel object work https://github.com/HARPgroup/HSPsquared/issues/77
   - [ ] Implement Gopal's new math if available (send email to him to see if he is ready to stash in github)
   - [ ] micro sub-watershed testing development https://github.com/HARPgroup/HSPsquared/issues/16
   - [ ] full BC test with simple routing & parsing
   - [ ] Imp work - https://github.com/HARPgroup/HSPsquared/issues/79
   - [ ] Extensive testing of header line in DataMatrix https://github.com/HARPgroup/HSPsquared/issues/26
   - [ ] Test broadcasts https://github.com/HARPgroup/HSPsquared/issues/36
   - [ ] Do testing branches to ascertain code bottlenecks https://github.com/HARPgroup/HSPsquared/issues/66
   - [ ] outline parser finalization
   - [ ] test runoff timeseries grabbing into ts_ix
   - [ ] Watershed/Sub-watershed model/river segment template development https://github.com/HARPgroup/HSPsquared/issues/58
   - [ ] Continue facility model migration script https://github.com/HARPgroup/vahydro/issues/844
   - [ ] Work on new version facility model https://github.com/HARPgroup/HARParchive/issues/744
   - [ ] Why does dynamic loading differ in Win/Lin? https://github.com/HARPgroup/HSPsquared/issues/73
   - [ ] Statistic https://github.com/HARPgroup/HSPsquared/issues/63
- [ ] VWP
   - [ ] Habitat in Cobb's/Henrico
   - [ ] continue Calibration analysis in Rapp #918 & #227
   - [ ] Also: https://github.com/HARPgroup/HARParchive/issues/1110
   - [ ] Get the basic TE set up for Motts to include all relevant segments #439
   - [ ] Bedford hydro coordination with Gouri #917
   - [ ] Attend VWP weekly meeting
- [ ] Drought:
   - [ ] #926
   - [ ] plan climate change scenario test https://github.com/HARPgroup/vahydro/issues/606
   - [ ] Update Drought mashup for Potomac https://github.com/HARPgroup/vahydro/issues/606#issuecomment-1591365841
   - [ ] Migrate met data and mashup processes into a meta_model workflow to allow multi-core with dependency at the landseg process step level
   - [ ] Test Rapp update/append WDM HARParchive/issues/173
   - [ ] Then do a 2nd version for p5 using append mode
   - [ ] https://github.com/HARPgroup/vahydro/issues/749
- [ ] General:
   - [ ] Save LEN https://github.com/HARPgroup/vahydro/issues/842 842
   - [ ] plan NHDplus to-node import to vahydro using column PlusFlowlineVAA_ToNode in file /var/www/html/files/nhd/NHDPlusFlowlines.csv (on deq1 and deq2)
   - [ ] CEDS Migration support
   - [ ] Get this book: https://link.springer.com/book/10.1007/978-1-4614-5833-3
   - [ ] Update [Gant chart on HSP2 project / sharepoint](https://covgov.sharepoint.com/:x:/s/deqnet/EaeMJ3KyRqZDuL5X2hA7ZSEB9Bk1DydneB966YeRQNu8QQ?e=kVekxs)
