### ISSUE TITLE
Week of 2023/12/11

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#943]
#### Main Goals
- Prepare presentation for S. Morris on exempt simulations in Rapidan/Rappahannock
- Mott's Run - my main modeling priority this week. Implement PoF because current approach leaves only 30 days of storage
- Push hsp2 model translation forward a wee bit, especially documenting integration steps to facilitate new modeler understanding and onboarding.

#### Tasks
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
   - [ ] Add hsp2_cbp5 to framework
   - [ ] Add hspf_cbp5 to framework
   - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)
- [ ] HARP Project
   - [ ] Plan baseline flow (zero withdrawal) model (see also https://github.com/HARPgroup/vahydro/issues/844 and https://github.com/HARPgroup/HARParchive/issues/744)
   - [ ] Come up with a good goal point to have a project demo and briefing for Hannah
- [ ] hsp2
   - [ ] Implement ModelObject with ACTIONS ops/STATE module integration https://github.com/respec/HSPsquared/issues/105
   - [ ] SimpleChannel object work https://github.com/HARPgroup/HSPsquared/issues/77
   - [ ] Implement Gopal's new math if available (send email to him to see if he is ready to stash in github)
   - [ ] micro sub-watershed testing development https://github.com/HARPgroup/HSPsquared/issues/16
   - [ ] full BC test with simple routing & parsing
   - [ ] Imp work - https://github.com/HARPgroup/HSPsquared/issues/79
   - [ ] Extensive testing of header line in DataMatrix https://github.com/HARPgroup/HSPsquared/issues/26
   - [ ] Test broadcasts https://github.com/HARPgroup/HSPsquared/issues/36
   - [ ] Do testing branches to ascertain code bottlenecks https://github.com/HARPgroup/HSPsquared/issues/66
   - [ ] outline parser finalization
   - [ ] test runoff timeseries grabbing into ts_ix
   - [ ] Watershed/Sub-watershed model/river segment template development https://github.com/HARPgroup/HSPsquared/issues/58
   - [ ] Continue facility model migration script https://github.com/HARPgroup/vahydro/issues/844
   - [ ] Work on new version facility model https://github.com/HARPgroup/HARParchive/issues/744
   - [ ] Why does dynamic loading differ in Win/Lin? https://github.com/HARPgroup/HSPsquared/issues/73
   - [ ] Statistic https://github.com/HARPgroup/HSPsquared/issues/63
- [ ] VWP
   - [ ] Habitat in Cobb's/Henrico
   - [ ] continue Calibration analysis in Rapp #918 & #227
   - [ ] Also: https://github.com/HARPgroup/HARParchive/issues/1110
   - [ ] Test Motts with PoF #439
   - [ ] Do 2 scenarios for whole Rapp to support analysis of exempt users meeting
   - [ ] Billesby-Buck scensrios https://github.com/HARPgroup/vahydro/issues/934
   - [ ] Work with G to develop approach and document rationale for "bypassed reach hydro" https://github.com/HARPgroup/vahydro/issues/934
- [ ] Drought:
   - [ ] #926
   - [ ] plan climate change scenario test https://github.com/HARPgroup/vahydro/issues/606
   - [ ] Update Drought mashup for Potomac https://github.com/HARPgroup/vahydro/issues/606#issuecomment-1591365841
   - [ ] Migrate met data and mashup processes into a meta_model workflow to allow multi-core with dependency at the landseg process step level
   - [ ] Test Rapp update/append WDM HARParchive/issues/173
   - [ ] Then do a 2nd version for p5 using append mode
   - [ ] https://github.com/HARPgroup/vahydro/issues/749
- [ ] General:
   - [ ] Database migration https://github.com/HARPgroup/vahydro/wiki/Database-Management
   - [ ] Save LEN https://github.com/HARPgroup/vahydro/issues/842 842
   - [ ] plan NHDplus to-node import to vahydro using column PlusFlowlineVAA_ToNode in file /var/www/html/files/nhd/NHDPlusFlowlines.csv (on deq1 and deq2)
   - [ ] CEDS Migration support
   - [ ] Get this book: https://link.springer.com/book/10.1007/978-1-4614-5833-3
   - [ ] Promote dbase3 to primary dbase
   - [ ] Update [Gant chart on WSP projects / sharepoint](https://covgov.sharepoint.com/:x:/s/deqnet/EaeMJ3KyRqZDuL5X2hA7ZSEB9Bk1DydneB966YeRQNu8QQ?e=kVekxs)
