### ISSUE TITLE
Week of 2024/02/12

### ISSUE THREAD

**Issue by rburghol** [HARPgroup/vahydro#971]
- Review spatial SQL for location QA with Brendan https://github.com/HARPgroup/vahydro/issues/334
- Begin setting up automated testing/continuous integration for the new model
- Verify habitat models are migrating and add automated summary scripts. 
- Pre-app meeting for Strasburg (hence habitat above)
- continue meteorology update
- Finalize plan for WA calculation work flow

#### Tasks
- [ ] meta-model control framework: https://github.com/HARPgroup/meta_model/issues/1
   - [ ] Add hsp2_cbp5 to framework
   - [ ] Add hspf_cbp5 to framework
   - [ ] carry over bug fix with ann/avg load calcs into p5 meta_model (if needed or is it just p6 thing?)
- [ ] HARP Project
   - [ ] Come up with a good goal point to have a project demo and briefing for Hannah
   - [ ] sketch out plan for where to calculate WA (in model run with other metric, or outside to specify the baseline run to use)
- [ ] hsp2
   - [ ] Watershed/Sub-watershed model/river segment template development https://github.com/HARPgroup/HSPsquared/issues/16
      - [ ] SimpleChannel object work https://github.com/HARPgroup/HSPsquared/issues/77
         - [ ] Implement Gopal's new math if available (send email to him to see if he is ready to stash in github)https://github.com/HARPgroup/HSPsquared/issues/58
      - [ ] Work out data model to insure that IVOL always traces dependencies appropriately
      - [ ] Flowby object https://github.com/HARPgroup/HSPsquared/issues/82
   - [ ] Imp work - https://github.com/HARPgroup/HSPsquared/issues/79
   - [ ] Extensive testing of header line in DataMatrix https://github.com/HARPgroup/HSPsquared/issues/26
   - [ ] Subsheds (add Bens Branch/Appalachia) https://github.com/HARPgroup/HARParchive/issues/739
   - [ ] Continue facility model migration script https://github.com/HARPgroup/vahydro/issues/844
   - [ ] Work on new version facility model https://github.com/HARPgroup/HARParchive/issues/744
   - [ ] Why does dynamic loading differ in Win/Lin? https://github.com/HARPgroup/HSPsquared/issues/73
   - [ ] Statistic https://github.com/HARPgroup/HSPsquared/issues/63
   - [ ] integration pull requests for OM components https://github.com/HARPgroup/HSPsquared/issues/80
   - [ ] Single Component end-point dependency tree https://github.com/respec/HSPsquared/issues/133
- [ ] WSP
   - [ ] baseline runs (full time period, then 1984-2014 as run 1000) #764 
      - [x] James
      - [x] New River
      - [x] Potomac
      - [ ] Rapp
      - [ ] York
      - [ ] Chowan
      - [x] Tennessee
- [ ] VWP
   - [ ] Habitat in Cobb's/Henrico
   - [ ] Also: https://github.com/HARPgroup/HARParchive/issues/1110
   - [ ] Cushaw #685 
   - [ ] Add WSP summary script running into every analysis I do for the next several weeks 
   - [ ] Appalachia reservoir #913 
   - [ ] review expiring permits and PEEP and update issue queue https://github.com/orgs/HARPgroup/projects/4/views/1
   - [ ] Veroify run 601 for beaverdam creek Eric https://github.com/HARPgroup/vahydro/issues/280
- [ ] Drought:
   - [ ] Download met data, update model through 2023
   - [ ] plan climate change scenario test https://github.com/HARPgroup/vahydro/issues/606
   - [ ] Update Drought mashup for Potomac https://github.com/HARPgroup/vahydro/issues/606#issuecomment-1591365841
   - [ ] Migrate met data and mashup processes into a meta_model workflow to allow multi-core with dependency at the landseg process step level
   - [ ] Test Rapp update/append WDM HARParchive/issues/173
   - [ ] Then do a 2nd version for p5 using append mode
   - [ ] https://github.com/HARPgroup/vahydro/issues/749
- [ ] General:
   - [ ] Save LEN https://github.com/HARPgroup/vahydro/issues/842 842
   - [ ] plan NHDplus to-node import to vahydro using column PlusFlowlineVAA_ToNode in file /var/www/html/files/nhd/NHDPlusFlowlines.csv (on deq1 and deq2)
   - [ ] CEDS Migration support
   - [ ] Get this book: https://link.springer.com/book/10.1007/978-1-4614-5833-3
   - [ ] Update [Gant chart on WSP projects / sharepoint](https://covgov.sharepoint.com/:x:/s/deqnet/EaeMJ3KyRqZDuL5X2hA7ZSEB9Bk1DydneB966YeRQNu8QQ?e=kVekxs)
